# Generated by Django 4.0 on 2021-12-29 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)])),
                ('live_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
