# Generated by Django 4.0 on 2021-12-29 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(blank=True, max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
